=== Doumbiaa/xml/catalogueMedia.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Catalogue de films et series -->
<!-- DTD Catalogue de films et series -->

<!-- premier niveeau -->
<!ELEMENT catalogueMedia (media+) >

<!-- deuxième niveeau -->
<!ELEMENT media (titre, type, annee, realisateur+, genres, duree?, saisons?, episodes? , disponible, description?) >

<!-- troisième niveeau -->
<!ELEMENT realisateur (nom, prenom) >
<!ELEMENT genres (genre)+ >

<!-- type des elements -->
<!ELEMENT titre (#PCDATA) >
<!ELEMENT type (#PCDATA) >
<!ELEMENT annee (#PCDATA) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT genre (#PCDATA) >
<!ELEMENT duree (#PCDATA) >
<!ELEMENT disponible (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT saisons (#PCDATA) >
<!ELEMENT episodes (#PCDATA) >

<!-- liste d'attributs -->
<!ATTLIST media id ID #REQUIRED >

=== Doumbiaa/xml/catalogueMedia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogueMedia SYSTEM "catalogueMedia.dtd">
<!-- Catalogue de films et séries -->
<catalogueMedia>
  <media id="M001">
    <titre>Inception</titre>
    <type>Film</type>
    <annee>2010</annee>
    <realisateur>
      <nom>Nolan</nom>
      <prenom>Christopher</prenom>
    </realisateur>
    <genres>
      <genre>Science-Fiction</genre>
      <genre>Thriller</genre>
    </genres>
    <duree>148</duree> <!-- en minutes -->
    <disponible>true</disponible>
    <description>Un voleur qui s’introduit dans les rêves des gens pour voler des secrets.</description>
  </media>

  <media id="M002">
    <titre>Stranger Things</titre>
    <type>Série</type>
    <annee>2016</annee>
    <realisateur>
      <nom>Duffer</nom>
      <prenom>Matt et Ross</prenom>
    </realisateur>
    <genres>
      <genre>Science-Fiction</genre>
      <genre>Horreur</genre>
      <genre>Drame</genre>
    </genres>
    <saisons>5</saisons>
    <episodes>43</episodes>
    <disponible>true</disponible>
    <description>Des enfants enquêtent sur des événements surnaturels dans leur ville.</description>
  </media>

  <media id="M003">
    <titre>The Godfather</titre>
    <type>Film</type>
    <annee>1972</annee>
    <realisateur>
      <nom>Coppola</nom>
      <prenom>Francis Ford</prenom>
    </realisateur>
    <genres>
      <genre>Crime</genre>
      <genre>Drame</genre>
    </genres>
    <duree>175</duree>
    <disponible>false</disponible>
    <description>La saga d'une famille mafieuse italo-américaine.</description>
  </media>
</catalogueMedia>
