=== Doumbiaa/xml/catalogueVoitures.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD catalogue voiture-->
<!-- www.linkedin.com/in/cheikh-doumbia -->

<!-- les niveaux -->
<!ELEMENT catalogueVoitures (voiture)+>
<!ELEMENT voiture (marque, modele, caracteristiques, prix)>
<!ELEMENT caracteristiques (moteur, couleur, places, portes)>

<!-- type des elements -->
<!ELEMENT marque (#PCDATA)>
<!ELEMENT modele (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
<!ELEMENT moteur (#PCDATA)>
<!ELEMENT couleur (#PCDATA)>
<!ELEMENT places (#PCDATA)>
<!ELEMENT portes (#PCDATA)>

<!-- liste d'attributs -->
<!ATTLIST voiture 
    id ID #REQUIRED
    disponible (oui | non) #REQUIRED
    type CDATA #REQUIRED
    >
<!ATTLIST moteur 
    cylindree CDATA #REQUIRED
    carburant CDATA #REQUIRED
    >
<!ATTLIST prix devise CDATA #REQUIRED>

=== Doumbiaa/xml/catalogueVoitures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogueVoitures SYSTEM "catalogueVoitures.dtd">
<!--catalogueVoitures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:noNamespaceSchemaLocation="catalogueVoitures.xsd"-->


 <catalogueVoitures>
  <voiture id="V001" disponible="oui" type="SUV">
    <marque>Toyota</marque>
    <modele>RAV4</modele>
    <caracteristiques>
      <moteur cylindree="2500" carburant="Essence"/>
      <couleur>Rouge</couleur>
      <places>5</places>
      <portes>5</portes>
    </caracteristiques>
    <prix devise="EUR">35000</prix>
  </voiture>

  <voiture id="V002" disponible="non" type="Berline">
    <marque>BMW</marque>
    <modele>Serie 3</modele>
    <caracteristiques>
      <moteur cylindree="2000" carburant="Diesel"/>
      <couleur>Noir</couleur>
      <places>5</places>
      <portes>4</portes>
    </caracteristiques>
    <prix devise="EUR">42000</prix>
  </voiture>
</catalogueVoitures>
